<?php
/**
 * Digit Software Solutions.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 *
 * @category  Dss
 * @package   Dss_LazyImageLoader
 * @author    Extension Team
 * @copyright Copyright (c) 2024 Digit Software Solutions. ( https://digitsoftsol.com )
 */
?>
<?php
/**
 * LazyImageLoader block
 *
 * @var  $block  \Dss\LazyImageLoader\Block\LazyLoad
 */
?>
<?php
$helper = $block->getHelper();
$escaper->escapeHtml($helper->getFullActionName());
$threshold = $helper->getThreshold();
?>
<?php if ($helper->isEnabled()): ?>
    <style>
        img.lazy {
            background: url(<?= $escaper->escapeHtml($helper->getLazyImage()); ?>) no-repeat;
            background-size: <?= $escaper->escapeHtml($helper->getLoadingWidth()); ?>px;
            background-position: center;
            width: 100%
        }
    </style>

    <script type="text/x-magento-init">
        {
            "*": {
                "Dss_LazyImageLoader/js/lazy_load": {
                    "threshold": "<?= /* @noEscape */ $threshold; ?>"
                }
            }
        }
    </script>

<?php endif; ?>
